### ISSUE TITLE
Text not readable in settings menus

### ISSUE THREAD

**Issue by masonlr** [obsidian-ezs/obsidian-ursa#4]
For example with v0.6.4

<img width="382" alt="image" src="https://user-images.githubusercontent.com/5828176/82895804-b61e6e80-9f4c-11ea-9312-ab914516979e.png">

**Comment by sigod** [comment]
Same issue in modals:
![image](https://user-images.githubusercontent.com/1175750/83422742-a6ae9200-a432-11ea-91bc-bd1c5d3b58f8.png)

**Comment by sigod** [comment]
Selection is barely visible in the command palette:
![image](https://user-images.githubusercontent.com/1175750/83446698-d02de480-a457-11ea-89ef-5e7990008eb2.png)

**Comment by WRoestorf** [comment]
Same issue in light mode (Obsidian version 0.74 on Windows 10):
1) In Tags list the tag count is barely readable
2) When you mouse over a tag in the tag list the tag is unreadable (just black block as in examples in above comments)
3) When in unlinked references list the "make linked reference" button that pops up when you mouse over an unlinked reference is also a black block

**Comment by rsomani95** [comment]
This should be fixed with PR #9 . All I did was add the following to the bottom of the file:
```css
.side-dock-collapsible-section-header:hover,
.tag-pane-tag:hover,
.pane-clickable-item:hover,
.suggestion-item:hover {
  background: var(--pre-code); /* tweak here for hover colors */
}

.modal.mod-settings button:not(.mod-cta) {
  color: var(--background-primary);
}
```
